-- MIGRATION 002 : OBSOLÈTE
-- La table session_seat_overrides n'a jamais été déployée en production.
-- Elle a été remplacée par session_seats (snapshot complet) avant tout déploiement.
-- Ce fichier est conservé pour l'historique uniquement — NE PAS EXÉCUTER.
