-- MIGRATION 004 : OBSOLÈTE
-- La table session_seats a été créée directement en production.
-- Elle fait maintenant partie du schema.sql officiel.
-- Ce fichier est conservé pour l'historique uniquement — NE PAS EXÉCUTER.
